PATCH http://localhost:8080/api/profile/name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwb29sYWVlbSIsInN1YiI6IkF1dGhlbnRpY2F0aW9uIiwiY29kZSI6InVzZXItMSIsImVtYWlsIjoidGVzdEBwb29sYWVlbS5jb20iLCJuYW1lIjoi7ZKA64K07J6EIiwiaWF0IjoxNjg3OTUyMTE4LCJleHAiOjM2ODc5NTM5MTh9.bE6RiK2Rpvr2JaYLhuFKnwP55rVUpWITOFfZncVAdLkD9SNlH2Wyn40ZSCgk8-EpWw3PjliMNjp5fTI6SD6izq5UiYrUxzf0fo9hMoP7eG091hL6nG-P9zwfrNOqOx9R15NNGQMEnjtcfaWmnbDCtM-pm1jjVF6ORIlkaqk_-R1Y7rqmfWex0qwf_NRrfL6d17QtjGU5CQumRDs-5eMCyF5Iq4ilv1Yp4o-IhZ2DlisUmoC9otTRNf3nqsv-O0CUQ2sko1AE3GWnsdpx9ht_Yx0ce5PA8-Ak-lDe29t-yXJrhKBjuIbHbtL9zqlrARM0yCYs01COZNLGOYFH8ba44g

{
  "userName": "update-username-sdfjksdfjksdfjsdfjksdfsd-fsdfksdfjksdfjksdjfksdjfsdf-sdfkjsdfkjsdkf"
}