POST http://localhost:8080/api/workbooks/01ee25fe37c84ee28d2a45504f474d66/solve
Content-Type: application/json

{
  "name" : "고길동",
  "problems": [
    {
      "problemId": "01ee2610504f4bfc8cdc87ad1a9e836d",
      "answers": [
        {
          "optionId": "01ee2610b954435a9cc67e6f3b3c6097",
          "answer": ["게임"]
        }
      ]
    }
  ]
}