spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            scope:
            - profile
            - email

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    clean-disabled: true

jwt:
  rsa:
    private: ${JWT_PRIVATE_KEY}
    public: ${JWT_PUBLIC_KEY}

