server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 100
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: bns-ssl
  http2:
    enabled: true

spring:
  application:
    name: poolaeem-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 16
          plan_parameter_metadata_max_size: 4
    hibernate:
      ddl-auto: none
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
            - profile
            - email

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    clean-disabled: true

jwt:
  rsa:
    private: ${JWT_PRIVATE_KEY}
    public: ${JWT_PUBLIC_KEY}

poolaeem:
  aws:
    s3:
      bucket-name: ${S3_BUCKET_NAME}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
  image:
    domain: ${POOLAEEM_IMAGE_DOMAIN}
  encrypt:
    secretKey: ${AES_ENCRYPT_SECRET_KEY}

management:
  server:
    port: ${ACTUATOR_PORT}
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: ${ACTUATOR_BASE_PATH}
      exposure:
        include: health,prometheus
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"


#grafana:
#  otlp:
#    on-prem:
#      endpoint: http://localhost:4317
#      protocol: grpc