name: Api Server Deploy

on:
  push:
    branches:
      - feat/#53-basic-ci-cd-by-githubaction
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        env:
          ECR_SERVER_URI: ${{ secrets.ECR_SERVER_URI }}
        run: ./gradlew -Pprofile=prod -PECR_SERVER_URL=$ECR_SERVER_URI jib -x test

