name: Api Server Deploy

on:
  push:
    branches:
      - api-develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Gradle
        run: ./gradlew -Pprofile=test clean test

      - name: Build with Gradle
        env:
          ECR_SERVER_URI: ${{ secrets.DEV_ECR_SERVER_URI }}
          LOKI_URL: ${{ secrets.LOKI_URL }}
          LOKI_USER: ${{ secrets.LOKI_USER }}
          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
        run: ECR_SERVER_URI=$ECR_SERVER_URI ./gradlew -Pprofile=prod clean jib -x test

      - name: Create Deployment on AWS CodeDeploy
        env:
          DEPLOY_APPLICATION_NAME: ${{ secrets.DEV_DEPLOY_APPLICATION_NAME }}
          DEPLOYMENT_GROUP_NAME: ${{ secrets.DEV_DEPLOYMENT_GROUP_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          DEPLOY_S3_BUCKET: ${{ secrets.DEV_DEPLOY_S3_BUCKET }}
          DEPLOY_S3_KEY: ${{ secrets.DEV_DEPLOY_S3_KEY }}
        run: aws deploy create-deployment --application-name $DEPLOY_APPLICATION_NAME --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$DEPLOY_S3_BUCKET,bundleType=zip,key=$DEPLOY_S3_KEY.zip



